### ISSUE TITLE
Make tests undefined reference to `ap_rprintf'

### ISSUE THREAD

**Issue by tvlooy** [tvlooy/cmocka_apache_module#1]
```bash
$ make test
rm -rf *.la *.lo *.slo .libs run_tests
gcc -o run_test mod_hello.c run_test.c \
    -lcmocka -lapr-1 -laprutil-1 \
    -I/usr/include/apache2 -I/usr/include/apr-1.0
/tmp/ccgCgA7c.o: In function `hello_register_hooks':
mod_hello.c:(.text+0x23): undefined reference to `ap_hook_quick_handler'
/tmp/ccgCgA7c.o: In function `hello_request_handler':
mod_hello.c:(.text+0x4d): undefined reference to `ap_rprintf'
collect2: error: ld returned 1 exit status
Makefile:17: recipe for target 'test' failed
make: *** [test] Error 1
```

It seems that I have to link ap_rprintf somehow but I don't know how. The function is declared in http_protocol.h ...

```
/usr/include/apache2/http_protocol.h:AP_DECLARE_NONSTD(int) ap_rprintf(request_rec *r, const char *fmt,...)
```

**Comment by cryptomilk** [comment]
As this is an Apache module I think the function is implemented in Apache itself. This means you need to allow linking with undefined symbols. -Wl,--allow-shlib-undefined -> man ld

**Comment by tvlooy** [comment]
@cryptomilk thanks for the tip. It compiles now so next step will be to try adding cmocha tests that actually test stuff, probably going to have to mock these missing functions ...
